config/routes.rb
Uif2013::Application.routes.draw do

  resources :shifts
  resources :department_trainings
  resources :volunteer_trainings
  resources :volunteer_checks
  resources :notes

  #require 'api_constraints' 
  
  # Barcode scanning routes
  match 'checkin', :controller => 'home', :action => 'checkin', :as => :checkin
  match 'volunteer_checkin', :controller => 'home', :action => 'volunteer_checkin', :as => :volunteer_checkin
  match 'meals_served', :controller => 'event', :action => 'meals_served'
  
  # General Home
  match 'home' => 'home#index', :as => :home
  match 'about' => 'home#about', :as => :about
  match 'contact' => 'home#contact', :as => :contact
  match 'privacy' => 'home#privacy', :as => :privacy
  match 'search' => 'home#search', :as => :search
  match 'statistics' => 'home#statistics', :as => :statistics
  match 'today' => 'events#today', :as => :today
  match 'tomorrow' => 'events#tomorrow', :as => :tomorrow
  match 'past' => 'events#past', :as => :past
 # get "events/today"


  
  # mobile routes
  resources :tokens,:only => [:create, :destroy]
  match 'getToken' => 'tokens#create', :via => :post
  match 'destroyToken' => 'tokens#destroy', :via => :delete
  match 'ajax_allergies' => 'allergies#ajax_allergies', :via => :get
  match 'getTodaysEvents' => 'mobile#getTodaysEvents', :via => :get
  match 'createAttendances' => 'mobile#createAttendances', :via => :post
  match 'getPhoto' => 'mobile#getPhoto', :via => :post
  match 'searchForStudent' => 'mobile#searchForStudent', :via => :get
  match 'getProgramsAndSections' => 'mobile#getProgramsAndSections', :via => :get
  match 'createEvent' => 'mobile#createEvent', :via => :post
  
  # Notes
  match 'alerts' => 'notes#alerts', :as => :alerts
  match 'dismiss_note/:id' => 'notes#dismiss', :as => :dismiss_note
  
  # Special attendance routes
  match 'mark_attended/:id' => 'events#mark_attended', :as => :mark_attended
  match 'mark_absent/:id' => 'events#mark_absent', :as => :mark_absent
  match 'mark_volunteer_attended/:id' => 'events#mark_volunteer_attended', :as => :mark_volunteer_attended
  match 'mark_volunteer_absent/:id' => 'events#mark_volunteer_absent', :as => :mark_volunteer_absent  

  # Drugs and conditions
  get "drug/index"


  #Generated model routes

  #resources :allergies
  resources :guardians do
    resources :notes
  end
  #resources :student_allergies
  resources :households do 
    resources :notes
  end
  resources :students do
    resources :notes
    get 'id', :on => :member
  end
  resources :drugs do
    resources :notes
  end
  resources :sections
  resources :attendances
  resources :locations do
    resources :notes
  end
  resources :events do
    resources :notes
    resources :shifts
    get 'meals_served', :on => :member
    get 'barcodes', :on => :member
  end
  resources :programs do
    resources :notes
    resources :shifts
  end
  resources :departments
  resources :enrollments
  resources :section_events
  #match 'volunteers/autocomplete_student_first_name' => 'volunteers#autocomplete_student_first_name'
  resources :volunteers do
    get :autocomplete_student_first_name, :on => :collection
    resources :notes
  end
  resources :trainings do
    resources:notes
  end
  resources :checks
  resources :conditions
  
  # Default URL
  root :to => 'home#index'
  
  # Authentication routes
  # resources :users
  devise_for :users
  # resources :sessions
  # match 'register' => 'users#new', :as => :register
  # match 'logout' => 'sessions#destroy', :as => :logout
  # match 'login' => 'sessions#new', :as => :login

end

app/models/training.rb
class Training < ActiveRecord::Base
    attr_accessible :description, :level, :name, :next_offered, :department_ids

    #Relationships
    has_many :volunteer_trainings, :dependent => :delete_all
    has_many :volunteers, :through => :volunteer_trainings
    has_many :department_trainings, :dependent => :delete_all
    has_many :departments, :through => :department_trainings
    has_many :notes, :as => :notable, :dependent => :destroy
    
    validates_presence_of :name
    validates_uniqueness_of :name
    
    scope :alphabetical, order('name')
    scope :for_training, lambda {|training_id| where("training_id = ?", training_id) }
    scope :for_check, lambda {|check_id| where("check_id = ?", check_id) }
    
end

app/controllers/trainings_controller.rb
class TrainingsController < ApplicationController
  # GET /trainings
  # GET /trainings.json
  def index
    @trainings = Training.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @trainings }
    end
  end

  # GET /trainings/1
  # GET /trainings/1.json
  def show
    @training = Training.find(params[:id])
      # get all the departments for this training
      @department_trainings = @training.department_trainings
      # get all the volunteers for this training

      @volunteer_trainings = @training.volunteer_trainings

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @training }
    end
  end

  # GET /trainings/new
  # GET /trainings/new.json
  def new
    @training = Training.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @training }
    end
  end

  # GET /trainings/1/edit
  def edit
    @training = Training.find(params[:id])
  end

  # POST /trainings
  # POST /trainings.json
  def create
    @training = Training.new(params[:training])

    respond_to do |format|
      if @training.save
        format.html { redirect_to @training, notice: 'Training was successfully created.' }
        format.json { render json: @training, status: :created, location: @training }
      else
        format.html { render action: "new" }
        format.json { render json: @training.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /trainings/1
  # PUT /trainings/1.json
  def update
    @training = Training.find(params[:id])

    respond_to do |format|
      if @training.update_attributes(params[:training])
        format.html { redirect_to @training, notice: 'Training was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @training.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trainings/1
  # DELETE /trainings/1.json
  def destroy
    @training = Training.find(params[:id])
    @training.destroy

    respond_to do |format|
      format.html { redirect_to trainings_url }
      format.json { head :no_content }
    end
  end
end

app/views/trainings/_current_departments.html.erb
<% if @department_trainings.empty? %>
There are no departments for this training at this time.
<p><br>
<% else %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Department</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @department_trainings.each do |department_training| %>
      <tr>
				<td><%= link_to department_training.department.name, department_path(department_training.department) %> </td>
	<td>
	<%= link_to raw("<i class='icon-trash'></i>"), department_training_path(department_training), :method => 'delete', :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn-small btn-danger' %></td>

      </tr>
    <% end %>
  </tbody>

</table>
<% end %>

app/views/trainings/_current_volunteers.html.erb
<% if @volunteer_trainings.empty? %>
There are no volunteers for this training at this time.
<p><br>
<% else %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Volunteer</th>
      <th>Date</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @volunteer_trainings.each do |volunteer_training| %>
      <tr>
				<td><%= link_to volunteer_training.volunteer.name, volunteer_path(volunteer_training.volunteer) %> </td>
				<td><%= link_to volunteer_training.date.strftime("%B %d, %Y") %> </td>
<td> <%= link_to raw("<i class='icon-edit'></i>"),
                      edit_volunteer_training_path(volunteer_training, :training_id => volunteer_training.training.id), :class => 'btn btn-mini' %> 
	<%= link_to raw("<i class='icon-trash'></i>"), volunteer_training_path(volunteer_training), :method => 'delete', :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn-small btn-danger' %></td>

      </tr>
    <% end %>
  </tbody>

</table>
<% end %>

app/views/trainings/_form.html.erb
<%= simple_form_for(@training) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description, :as => :text, :input_html => { :cols => 150, :rows => 5 }%>
    <%= f.input :level, :as => :radio_buttons, :collection => [["Beginner ","Beginner "], ["Intermediate ","Intermediate "], ["Advanced ","Advanced "]], :item_wrapper_class => 'inline' %> 
    <%= f.input :next_offered, :order => [:month, :day, :year], :start_year => Date.today.year+2, :end_year => Date.today.year %>
  </div>

<br>
<p>Departments this Training belongs to:</p>
<p>
	<%#(Select All javascript! Implement F13) check_box_tag('check_all', 'check_all', false,  :onClick => "$$('#my_form input.check').each(function(box){box.checked=($('check_all').checked)?true:false});")%>
	
<br>

  <% for department in Department.alphabetical %>
    <%= check_box_tag "training[department_ids][]", department.id, @training.departments.include?(department) %>
    <%= department.name %>
    <br />
  <% end  %>


</p>


  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/trainings/edit.html.erb
<h1>Editing Training</h1>

<%= render 'form' %>

<%= link_to 'Show', @training %> |
<%= link_to 'Back', trainings_path %>

app/views/trainings/index.html.erb
    <%= link_to raw("<i class='icon-plus'></i> <strong>Add Training</strong>"), new_training_path, :class => 'btn btn-success pull-right' %>

<h1>Listing trainings</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Level</th>
      <th>Description</th>
      <th></th>
    </tr>
  </thead>

  <tbody id="list">
    <% @trainings.each do |training| %>
      <tr>
        <td><%= link_to training.name, training %></td>
        <td><%= training.level %></td>
        <td><%= training.description %></td>
        <td><%= link_to raw("<i class='icon-file'></i>"), new_note_path(:id => training.id, :source => 'training'), :class => 'btn btn-mini' %>
        &nbsp;<%= link_to raw("<i class='icon-pencil'></i>"),edit_training_path(training), :class => 'btn btn-mini' %></td>
  </tr>
<% end %>

  </tbody>


</table>

<br />

app/views/trainings/new.html.erb
<h1>New training</h1>

<%= render 'form' %>

<%= link_to 'Back', trainings_path %>

app/views/trainings/show.html.erb
<h1>Training Details </h1>

<p>
  <b>Name:</b>
  <%= @training.name %>
</p>

<p>
  <b>Description:</b>
  <%= @training.description %>
</p>

<p>
  <b>Level:</b>
  <%= @training.level %>
</p>

<p>
  <b>Next Offered:</b>
  <%= @training.next_offered.strftime("%B %d, %Y") %>
</p>



<div class="row-fluid">
  
  <div class="span4">

<p>              <%= render :partial => "current_departments" %> </p>

<p> 		<%= link_to raw("<i class='icon-plus icon-white'></i> <strong>Assign Department</strong>"), new_department_training_path(:id => @training.id, :from => 'training'), :class => 'btn-small btn-success' %> </p>


</div>  <div class="span8">
<p>              <%= render :partial => "current_volunteers" %> </p>
<p> 		<%= link_to raw("<i class='icon-plus icon-white'></i> <strong>Assign Volunteer</strong>"), new_volunteer_training_path(:id => @training.id, :from => 'training'), :class => 'btn-small btn-success' %> </p>

</div></div>

<div class="form-actions">
  <%= link_to raw("<i class='icon-backward'></i> Back to trainings"),
              trainings_path, :class => 'btn'  %>
  <%= link_to raw("<i class='icon-edit'></i> Edit this training"),
              edit_training_path(@training), :class => 'btn' %>
  <%= link_to raw("<i class='icon-remove'></i> Destroy this training"),
              training_path(@training),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>