config/routes.rb
Uif2013::Application.routes.draw do

  resources :shifts
  resources :department_trainings
  resources :volunteer_trainings
  resources :volunteer_checks
  resources :notes

  #require 'api_constraints' 
  
  # Barcode scanning routes
  match 'checkin', :controller => 'home', :action => 'checkin', :as => :checkin
  match 'volunteer_checkin', :controller => 'home', :action => 'volunteer_checkin', :as => :volunteer_checkin
  match 'meals_served', :controller => 'event', :action => 'meals_served'
  
  # General Home
  match 'home' => 'home#index', :as => :home
  match 'about' => 'home#about', :as => :about
  match 'contact' => 'home#contact', :as => :contact
  match 'privacy' => 'home#privacy', :as => :privacy
  match 'search' => 'home#search', :as => :search
  match 'statistics' => 'home#statistics', :as => :statistics
  match 'today' => 'events#today', :as => :today
  match 'tomorrow' => 'events#tomorrow', :as => :tomorrow
  match 'past' => 'events#past', :as => :past
 # get "events/today"


  
  # mobile routes
  resources :tokens,:only => [:create, :destroy]
  match 'getToken' => 'tokens#create', :via => :post
  match 'destroyToken' => 'tokens#destroy', :via => :delete
  match 'ajax_allergies' => 'allergies#ajax_allergies', :via => :get
  match 'getTodaysEvents' => 'mobile#getTodaysEvents', :via => :get
  match 'createAttendances' => 'mobile#createAttendances', :via => :post
  match 'getPhoto' => 'mobile#getPhoto', :via => :post
  match 'searchForStudent' => 'mobile#searchForStudent', :via => :get
  match 'getProgramsAndSections' => 'mobile#getProgramsAndSections', :via => :get
  match 'createEvent' => 'mobile#createEvent', :via => :post
  
  # Notes
  match 'alerts' => 'notes#alerts', :as => :alerts
  match 'dismiss_note/:id' => 'notes#dismiss', :as => :dismiss_note
  
  # Special attendance routes
  match 'mark_attended/:id' => 'events#mark_attended', :as => :mark_attended
  match 'mark_absent/:id' => 'events#mark_absent', :as => :mark_absent
  match 'mark_volunteer_attended/:id' => 'events#mark_volunteer_attended', :as => :mark_volunteer_attended
  match 'mark_volunteer_absent/:id' => 'events#mark_volunteer_absent', :as => :mark_volunteer_absent  

  # Drugs and conditions
  get "drug/index"


  #Generated model routes

  #resources :allergies
  resources :guardians do
    resources :notes
  end
  #resources :student_allergies
  resources :households do 
    resources :notes
  end
  resources :students do
    resources :notes
    get 'id', :on => :member
  end
  resources :drugs do
    resources :notes
  end
  resources :sections
  resources :attendances
  resources :locations do
    resources :notes
  end
  resources :events do
    resources :notes
    resources :shifts
    get 'meals_served', :on => :member
    get 'barcodes', :on => :member
  end
  resources :programs do
    resources :notes
    resources :shifts
  end
  resources :departments
  resources :enrollments
  resources :section_events
  #match 'volunteers/autocomplete_student_first_name' => 'volunteers#autocomplete_student_first_name'
  resources :volunteers do
    get :autocomplete_student_first_name, :on => :collection
    resources :notes
  end
  resources :trainings do
    resources:notes
  end
  resources :checks
  resources :conditions
  
  # Default URL
  root :to => 'home#index'
  
  # Authentication routes
  # resources :users
  devise_for :users
  # resources :sessions
  # match 'register' => 'users#new', :as => :register
  # match 'logout' => 'sessions#destroy', :as => :logout
  # match 'login' => 'sessions#new', :as => :login

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  respond_to :html, :json, :js
  before_filter :set_controller_and_action_names
  
  def index
   @events = Event.upcoming
   @events_last_week = Event.last_week
   @students = Student.not_visitor
   @volunteers = Volunteer.alphabetical
      @pending_checks = VolunteerCheck.pending
      @expiring_checks = VolunteerCheck.expiring
   @households = Household.active
   @shifts = Shift.last_week
   @hours = 0
   @absences_last_week = 0
   @attendees_last_week = 0
   @past = Event.past.by_date_desc.limit(2)
   @sections = Section.active
   @alerts = Note.alerts.active.by_priority.by_date_desc.last_six.all
   @alert_count = Note.alerts.active.all.length
   @student_alerts = Note.active.student_alerts.length
   @volunteer_alerts = Note.active.volunteer_alerts.length
   @event_alerts = Note.active.event_alerts.length
   @visitors = Student.is_visitor
  
  
  end 

  def about
  end

  def contact
  end

  def search
   @query = params[:query]
   @students = Student.fuzzy_match(@query)
   @volunteers = Volunteer.fuzzy_match(@query)
   @guardians = Guardian.fuzzy_match(@query)
   @student_hits = @students.size
   @volunteer_hits = @volunteers.size
   @guardian_hits = @guardians.size
   @total_hits = @students.size + @volunteers.size + @guardians.size
  end

def checkin
    session[:event] = params[:event_id]
    @event = Event.find(session[:event])
    if @event.program.scan_by_absence && session[session[:event].intern].nil?
      @absent_students = Event.student_absentees(session[:event])
      if(!@absent_students.nil?)
        @absent_students.each do |student|
          student.attendances.create(event_id: session[:event])
        end
      end    
      @student_attendees = Event.student_attendees(session[:event])
      @student_absentees = Event.student_absentees(session[:event])
      session[session[:event].intern] = 1;
    else
      @student_attendees = Event.student_attendees(session[:event])
      @student_absentees = Event.student_absentees(session[:event])
    end
    
    if !@event.program.scan_by_absence && params[:barcode] && session[:event]
      @student = Student.find_by_barcode_number(params[:barcode])
      if @student && @student.attendances.create(event_id: params[:event_id])
        if @student.is_visitor
          note = Note.new
          note.user_id = current_user.id
          note.date = Date.today
          note.contents = "#{@student.proper_name} is a new visitor attending an event for #{@event.program.name}."
          note.notable_type = "Event"
          note.notable_id = @event.id
          note.priority = 2
          note.title = "Visitor #{@student.proper_name} Attended Event"
          note.active = true
          note.save
        end
        
        @student_attendances = Event.student_attendees(session[:event])
        @student_absences = Event.student_absentees(session[:event])
        if(!@student_absences.nil?) 
          @student_absences.each do |student|
            puts student.proper_name if !student.nil?
          end
        end
        render :json => { message: "#{@student.proper_name} was successfully scanned!", student: @student, attendees: @attendances, absentees: @absences }
        #render :json => { message: "#{@student.proper_name} was successfully scanned!", attendees: @student_attendances, absentees: @student_absences }
      else
        render :json => { error:'There was an error scanning.'}
      end    
    end
    
    if @event.program.scan_by_absence && params[:barcode] && session[:event]
      @student = Student.find_by_barcode_number(params[:barcode])
      if @student
        @student_attendance = Attendance.find_by_student_id_and_event_id(@student.id,session[:event])
        if(!@student_attendance.nil?)
          if @student.attendances.destroy(@student_attendance.id)
            @student_attendees = Event.student_attendees(session[:event])
            @student_absentees = Event.student_absentees(session[:event])
            render :json => { message: "#{@student.proper_name} did not attend!", attendees: @student_attendees, absentees: @student_absentees }
          elsif
            render :json => { error:'There was an error scanning.', message:  "#{@student.proper_name} was not scanned. Try again."}
          end
        else  
          @student_attendees = Event.student_attendees(session[:event])
          @student_absentees = Event.student_absentees(session[:event])
          render :json => { message:"#{@student.proper_name} is already absent.",attendees: @student_attendees, absentees: @student_absentees }
        end
      else
        render :json => { error:'There was an error scanning.' }
      end    
    end
  end

  
def volunteer_checkin
    session[:event] = params[:event_id]
    @event = Event.find(session[:event])
    @volunteer_attendees = Event.volunteer_attendees(session[:event])
    @volunteer_absentees = Event.volunteer_absentees(session[:event])
    if params[:barcode] && session[:event]
      @volunteer = Volunteer.find_by_barcode_number(params[:barcode])
      if @volunteer
        @shift = @volunteer.shifts.where("shiftable_type = ? AND shiftable_id = ?","Event",params[:event_id]).first
        @shift.checked_in = true
        if @shift.save
          @volunteer_attendees = Event.volunteer_attendees(session[:event])
          @volunteer_absentees = Event.volunteer_absentees(session[:event])
          if(!@volunteer_absentees.nil?) 
            @volunteer_absentees.each do |volunteer|
              puts volunteer.proper_name if !volunteer.nil?
            end
          end
          render :json => { message: "#{@volunteer.proper_name} was successfully scanned!", volunteer_attendees: @volunteer_attendees, volunteer_absentees: @volunteer_absentees }
        end
      else
        render :json => { error:'HERE.There was an error scanning.' }
      end
    end
  end

  def statistics
    @department = Department.all
    months = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']
    if !params[:date].nil?
      month = params[:date][:month]
      
      @w_month = months[month.to_i-1]
      year = params[:date][:year]

      @attendance_by_month_year = ActiveRecord::Base.connection.execute('SELECT d.name AS department, programs.name AS program, COUNT(a.id) AS attendances FROM "programs" INNER JOIN departments d ON d.id = programs.department_id LEFT JOIN events e ON e.program_id = programs.id LEFT JOIN attendances a ON a.event_id = e.id WHERE (EXTRACT(MONTH from date)::int = '+month+' AND EXTRACT(YEAR from date)::int ='+year+') GROUP BY d.name, programs.name ORDER BY department, program')
     
     @total_attendance_by_month_year =  ActiveRecord::Base.connection.execute('SELECT d.name AS department, COUNT(a.id) AS attendances FROM "programs" INNER JOIN departments d ON d.id = programs.department_id LEFT JOIN events e ON e.program_id = programs.id LEFT JOIN attendances a ON a.event_id = e.id WHERE (EXTRACT(MONTH from date)::int = '+month+' AND EXTRACT(YEAR from date)::int ='+year+') GROUP BY d.name ORDER BY d.name')
      
      @events_by_month_year = ActiveRecord::Base.connection.execute('SELECT d.name AS department, programs.name AS program, SUM(e.meals_served) AS meals, SUM(e.bibles_distributed) AS bibles, SUM(CASE WHEN e.gospel_shared = \'t\' THEN 1 ELSE 0 END) AS gospel FROM "programs" INNER JOIN departments d ON d.id = programs.department_id LEFT JOIN events e ON e.program_id = programs.id WHERE (EXTRACT(MONTH from date)::int = '+month+' AND EXTRACT(YEAR from date)::int = '+year+') GROUP BY d.id, programs.id ORDER BY d.name, programs.name')
      
      @total_events_by_month_year = ActiveRecord::Base.connection.execute('SELECT d.name AS department, SUM(e.meals_served) AS meals, SUM(e.bibles_distributed) AS bibles, SUM(CASE WHEN e.gospel_shared = \'t\' THEN 1 ELSE 0 END) AS gospel FROM "programs" INNER JOIN departments d ON d.id = programs.department_id LEFT JOIN events e ON e.program_id = programs.id WHERE (EXTRACT(MONTH from date)::int = '+month+' AND EXTRACT(YEAR from date)::int = '+year+') GROUP BY d.id ORDER BY d.name')
       
      @join = @attendance_by_month_year.zip(@events_by_month_year)
      
      @join_total = @total_attendance_by_month_year.zip(@total_events_by_month_year)
      
      #YTD statistics
      if (9..12).include?(month.to_i)
        @ytd_by_program_attendance = ActiveRecord::Base.connection.execute('SELECT d.name AS department, programs.name AS program, COUNT(a.id) AS attendances FROM "programs" INNER JOIN departments d ON d.id = programs.department_id LEFT JOIN events e ON e.program_id = programs.id LEFT JOIN attendances a ON a.event_id = e.id WHERE (EXTRACT(MONTH from date)::int >= 9 AND EXTRACT(MONTH from date)::int <= '+month+' AND EXTRACT(YEAR from date)::int ='+year+') GROUP BY d.name, programs.id ORDER BY d.name, programs.name')
        
        @ytd_by_program_event = ActiveRecord::Base.connection.execute('SELECT d.name AS department, programs.name AS program, SUM(e.meals_served) AS meals, SUM(e.bibles_distributed) AS bibles, SUM(CASE WHEN e.gospel_shared = \'t\' THEN 1 ELSE 0 END) AS gospel FROM "programs" INNER JOIN departments d ON d.id = programs.department_id LEFT JOIN events e ON e.program_id = programs.id WHERE (EXTRACT(MONTH from date)::int >=9 AND EXTRACT(MONTH from date)::int <= '+month+' AND EXTRACT(YEAR from date)::int = '+year+') GROUP BY d.name, programs.id ORDER BY d.name, programs.name')
        

app/views/home/_admin_home.html.erb
<!-- if your role is an admin -->

<div class="metrouicss">
  <div class="tiles">
    <div class="tile-group">
      <div class="dashboard">
      <div id="big-tile" class="tile">
	<div class="tile-content"><h2>Events</h2>
	  <ul id="tabs" class="nav nav-tabs" data-tabs="tabs">
		  <li class="active"><a href="#red" data-toggle="tab">Today</a></li>
		  <li><a href="#orange" data-toggle="tab">Past</a></li>
	      </ul>
	      <div id="my-tab-content" class="tab-content">
		  <div class="tab-pane active" id="red">
		      <% if @events.current.empty? %> 
		      <%= render :partial => "./admin-partials/upcoming-events" %>
		      <% else %><%= render :partial => "./admin-partials/upcoming-events" %><% end %>
		  </div>
		  <div class="tab-pane" id="orange">
		      <%= render :partial => "./admin-partials/past-events" %>
		  </div>

	      </div>
      </div></div>
      <div class="tile" id="visitor"><a href="students.html">
	<div class="tile-content"><h1>Visitors</h1>
	  <li>New visitors: <%= @visitors.new_visitor.count %></li>
	  <li><%= link_to "Add visitor", new_student_path %></li>
      </div></div>
      <div class="tile" id="student"><a href="students.html">
	<div class="tile-content"><h1>Student</h1>
	    <% for event in @events_last_week %>
	  	  <% unless Event.student_absentees(event.id).nil? %>
	   		 <% @absences_last_week = @absences_last_week + Event.student_absentees(event.id).size %>
	    	  <% end %>
 	    <% end %>
 	    <% if @absences_last_week==0 && @student_alerts==0 %>
	      All is good
	      <% else %>
		<% unless @absences_last_week ==0 %>
		  <li>Absences Last Week: <%= @absences_last_week %></li>
		<% end %>
		<% unless @student_alerts==0 %>
		  <li>Student Alerts: <%= @student_alerts %></li>
		<% end %>
	      <% end %>

      </div></div>
      <div class="tile" id="volunteer"><a href="volunteers.html">
	<div class="tile-content"><h1>Volunteer</h1>
	  <% if @pending_checks.empty? && @volunteer_alerts==0 && @expiring_checks.empty? %>
	    All is good
	    <% else %>
	      <% unless @pending_checks.empty? %>
		<li>Pending Checks: <%= @pending_checks.length %></li>
	      <% end %>
	      <% unless @volunteer_alerts==0 %>
		<li>Volunteer Alerts: <%= @volunteer_alerts %></li>
	      <% end %>
	      <% unless @expiring_checks.empty? %>
		<li>Expiring Checks: <%= @expiring_checks.length %></li>
	      <% end %>

	    <% end %>
      </div></div>
      <div class="tile" id="event"><a href="events.html">
	<div class="tile-content"><h1>Event</h1>
	  <li><% if @events.current.empty? %>
	    No events today
	  <% else %>
	    Today: <%= @events.current.count %>
	  <% end %></li>
	  <li><% if @events.this_week.empty? %> No events next week
	  <% else %>This week: <%= @events.this_week.count %><% end %></li>
	  <% unless @events.religious.empty? %> 
	  <li>Upcoming Religious Events: <%= @events.this_week.religious.count %></li><% end %>
	  <% unless @event_alerts==0 %>
	    <li>Event Alerts: <%= @event_alerts %></li>
	  <% end %>  
      </div></div>
      <div id="tall-tile" class="tile"><a href="statistics.html">
	<div class="tile-content"><h1>Statistics</h1>
	  <h3>For the past week</h3>

	    <% for event in @events_last_week %>
	  	  <% unless Event.student_attendees(event.id).nil? %>
	   		 <% @attendees_last_week = @attendees_last_week + Event.student_attendees(event.id).size %>
	    	  <% end %>
 	    <% end %>

	  <li>Attendees Last Week: <%= @attendees_last_week %></li>
	  <li>Absences Last Week: <%= @absences_last_week %></li>


	   <% unless @absences_last_week.zero? %>

	  <li>Student Attendance Percentage: <%= ((@attendees_last_week.to_f / (@absences_last_week + @attendees_last_week))*100).to_i %>%</li>	  
 	    <% end %>

	  <li>Events Last Week: <%= @events_last_week.length %></li>
	  <% for shift in @shifts %>
	    <% @hours = @hours + shift.hours %>
	    <% end %>
	  <li>Volunteer Hours : <%= @hours %></li>
	  <li>New Students : <%= @students.new_student.count %></li>
	  <li>New Volunteers : <%= @volunteers.new_volunteer.count %></li>
      </div></div>
      <div class="tile" id="program"><a href="sections">
	<div class="tile-content"><h1>Program Sections</h1>
	  <li><% if @sections.maxed_out.empty? %> Sections are available
	  <% else %>Maxed out sections: <%= @sections.maxed_out.length %><% end %></li>
	  <% unless @sections.empty_sections.empty? %><li>
	    Empty sections: <%= @sections.empty_sections.length %></li><% end %>
	</div></div>
      <div class="tile" id="household"><a href="households.html">
	<div class="tile-content"><h1>Household</h1>
	  <% if @households.missing_info.empty? %>
	    All is good
	  <% else %>
	    <li>Missing insurance info: <%= @households.missing_info.length %></li>
	  <% end %>
      </div></div>
      <div class="tile" id="guardian"><a href="guardians.html">
	<div class="tile-content"><h1>Guardian</h1>
	  All is good
      </div></div>
    </div>
  </div></div>
</div>



<script type="text/javascript">
  $(function() {
	   $('.phantom').hide();
	});
</script>

app/views/home/_attendees.html.erb
<% if @student_attendees.nil? %>
<h4>No Attendees</h4>
<% else %>
<table id="attendees" class="table table-striped">
  <thead>
    <tr>
      <th>Student</th>
      <th>Phone Number</th>
      <th>Barcode Number</th>
      <th>&nbsp;</th>
    </tr>
  </thead>
  <tbody>
    <% @student_attendees.each do |student| %>
      <tr>
        <td><%= link_to student.name, student_path(student) %></td>
        <%- if student.cell_phone.nil? -%>
          <td>No Phone Number</td> 
        <% else %>
          <td><%= number_to_phone student.cell_phone %></td> 
        <% end %> 
        <td><% if student.is_visitor %> <i class="icon-flag"></i><%end%><%= student.barcode_number %></td>    
        <td><%= link_to raw("<i class='icon-file'></i> Add note"), new_note_path(:id => student.id, :source => 'student'), :class => 'btn btn-mini' %>
        </td>        
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>

app/views/home/_scan_profile.html.erb
<%- model_class = Student -%>

<div class="scan-profile">

	<div class="span4" id="scan-profile-avatar">
		
		<<% if !@student.avatar_file_name.blank? %>
		    <div class="img-polaroid"><%= image_tag @student.avatar.url(:medium) %></div>
		  <% else %>
		    <% if @student.is_male %>
		      <div class="img-polaroid"> <%= image_tag("male.jpg") %></div>&nbsp;&nbsp;
		    <% else %>  
		      <div class="img-polaroid"> <%= image_tag("female.jpg") %></div>&nbsp;&nbsp;
		    <% end %>
		<% end %>
		
	</div>

	<div class="span8" id="scan-profile-information">
		<h1><%= @student.proper_name %></h1>
		<div class="scan-profile-student-information">
			
		</div>
	</div>

	<div id="scan-profile-bottom">
		<div class="scan-profile-student-warning">
		</div>
		<div class="scan-profile-student-condition">
		</div>
	</div>

</div>

app/views/home/_volunteer_absentees.html.erb
<% if @volunteer_absentees.nil? %>
<h4>No Absentees</h4>
<% else %>
<table id="volunteer_absentees" class="table table-striped">
  <thead>
    <tr>
      <th>Student</th>
      <th>Phone Number</th>
      <th>Barcode Number</th>
      <th>&nbsp;</th>
    </tr>
  </thead>
  <tbody>
    <% @volunteer_absentees.each do |volunteer| %>
      <tr>
        <td><%= link_to volunteer.name, volunteer_path(volunteer) %></td>
        <%- if volunteer.cell_phone.nil? -%>
          <td>No Phone Number</td> 
        <% else %>
          <td><%= number_to_phone volunteer.cell_phone %></td> 
        <% end %> 
       <td><%= volunteer.barcode_number %></td>     
        <td><%= link_to raw("<i class='icon-file'></i> Add note"), new_note_path(:id => volunteer.id, :source => 'volunteer'), :class => 'btn btn-mini' %>
        </td>           
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>

app/views/home/_volunteer_attendees.html.erb
<% if @volunteer_attendees.nil? %>
<h4>No Attendees</h4>
<% else %>
<table id="volunteer_attendees" class="table table-striped">
  <thead>
    <tr>
      <th>Volunteer</th>
      <th>Phone Number</th>
      <th>Barcode Number</th>
      <th>&nbsp;</th>
    </tr>
  </thead>
  <tbody>
    <% @volunteer_attendees.each do |volunteer| %>
      <tr>
        <td><%= link_to volunteer.name, volunteer_path(volunteer) %></td>
        <%- if volunteer.cell_phone.nil? -%>
          <td>No Phone Number</td> 
        <% else %>
          <td><%= number_to_phone volunteer.cell_phone %></td> 
        <% end %> 
        <td><%= volunteer.barcode_number %></td>    
        <td><%= link_to raw("<i class='icon-file'></i> Add note"), new_note_path(:id => volunteer.id, :source => 'volunteer'), :class => 'btn btn-mini' %>
        </td>        
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>

app/views/home/about.html.erb
<h1>About UIF</h1>


<p>	
Under construction.
</p>

app/views/home/checkin.html.erb
<div class="adjust_page">
  <div class="page-header checkin">
  <h2><%= @event.date.strftime("%b %d, %Y") %></h2>
  <%= link_to "Scan Volunteers for this event", {:controller => "home", :action => "volunteer_checkin", :event_id => @event.id}%>
  <%- if @event.program.scan_by_absence %>
    <h2>Absence Scan for Following Sections:</h2>
  <%- else %>
    <h3>Attendance Scan for Following Sections:</h3>
  <%- end %>
  </div>
  <ul class="scan_sections">
  <% @event.sections.each do |event| %>
    <li><%= event.name %></li>
  <% end %>
  </ul>
  <br/>
  <h5>Scanning...</h5>
  <div class="span3" id="attendance_barcodes">
        <input id ="Input" type="text"> </input>
        <h3 style="color: black;"><span id="student_checked"></span></h3>
  </div>
  <div class="span9" id="scan_profile">
    <% student = @student || Student.new %>
    <div class="scanning student"><div id="profile"><%= render :partial => "scan_profile", locals:{student: student} %></div></div>
  </div>
  <br/>
  <div id="container">
    <div class="scanning attend"><h2>Attendees</h2><p/><div id="attend"><%= render :partial => "attendees" %></div></div>
    <div class="scanning absent"><h2>Absentees</h2><p/><div id="absent"><%= render :partial => "absentees" %></div></div>
  </div>
</div>

app/views/home/index.html.erb
<% if current_user && current_user.is_admin? %>
  <%= render :partial => "admin_home" %>
<% else %>
  <%= render :partial => "general_home" %>
<% end %>

app/views/home/loginpage.html.erb
<!--<h1>Home#index</h1> -->
<!--<p>Find me in app/views/home/index.html.erb</p> -->

<div class="hero-unit"><h3>Login </h3>
<form class="form-horizontal">
  <div class="control-group">
    <label class="control-label" for="inputEmail">Email</label>
    <div class="controls">
      <input type="text" id="inputEmail" placeholder="Email">
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="inputPassword">Password</label>
    <div class="controls">
      <input type="password" id="inputPassword" placeholder="Password">
    </div>
  </div>
  <div class="control-group">
    <div class="controls">
      <label class="checkbox">
        <input type="checkbox"> Remember me
      </label>
      <button type="submit" class="btn">Sign in</button>
    </div>
  </div>
</form>
</div>

app/views/home/search.html.erb
<h1>Search Result</h1>
<h2>Search result for term <em>'<%= @query %>'</em> resulted in <%= pluralize(@total_hits, 'hit') %></h2>
<div class="row-fluid">
	<div class="span6">
		<!--student: name, phone, pic-->
		<p><em><strong><%= @student_hits %> students found.</strong></em></p>
		<% unless @students.empty? %>
		<ul class="no_bullet">
		<% for student in @students do %>
			<div class="well search_box">
				<div class="row">
					<div class="span2">
						<% if !student.avatar_file_name.blank? %>
        					<div><%= image_tag student.avatar.url(:medium), :size => "60x50", :border => 0 %></div>
        				<% elsif student.is_male %>
          					<div> <%= image_tag("male.jpg", :size => "60x50", :border => 0) %></div>&nbsp;&nbsp;
        				<% else %>  
          					<div> <%= image_tag("female.jpg", :size => "60x50", :border => 0) %></div>&nbsp;&nbsp;
        				<% end %>
      				</div>
      				<div class="span4">
						<li>Name: <%= link_to student.proper_name, student_path(student) %></li>
						<li>Cell: 
							<%= student.cell_phone.blank? ? "N/A" : number_to_phone(student.cell_phone) %>
             			</li>
					</div>
				</div>
			</div>
		<% end %>		
		</ul>
		<p class="smtext">&nbsp;</p>
		<% end %>
		<!--guardian: name, children-->
		<p><em><strong><%= @guardian_hits %> guardians found.</strong></em></p>
		<% unless @guardians.empty? %>
		<ul>
		<% for guardian in @guardians do %>
			<li>Name: <%= link_to guardian.proper_name, guardian_path(guardian) %></li>
			<li>&nbsp;&nbsp;&nbsp;Children: 
				<%= guardian.my_children.map(&:proper_name).join(',') %></li>
		<% end %>
		</ul>
		<% end %>
	</div>
	<div class="span6">
		<!--volunteers: name, phone-->
		<p><em><strong><%= @volunteer_hits %> volunteers found.</strong></em></p>
		<% unless @volunteers.empty? %>
		<ul class="no_bullet">
		<% for volunteer in @volunteers do %>
			<div class="well search_box">
				<div class="row">
					<div class="span2">
						<% if !volunteer.avatar_file_name.blank? %>
        					<div><%= image_tag volunteer.avatar.url(:medium), :size => "60x50", :border => 0 %></div>
        				<% elsif volunteer.is_male %>
          					<div> <%= image_tag("male.jpg", :size => "60x50", :border => 0) %></div>&nbsp;&nbsp;
        				<% else %>  
          					<div> <%= image_tag("female.jpg", :size => "60x50", :border => 0) %></div>&nbsp;&nbsp;
        				<% end %>
      				</div>
      				<div class="span4">
						<li>Name: <%= link_to volunteer.proper_name, volunteer_path(volunteer) %></li>
						<li>Cell: 
							<%= volunteer.cell_phone.blank? ? "N/A" : number_to_phone(volunteer.cell_phone) %>
             			</li>
					</div>
				</div>
			</div>
		<% end %>		
		</ul>
		<% end %>
	</div>
</div>

app/views/home/statistics.js.erb
  console.log('Success');
  $("#stat_tables").hide().html("<%= escape_javascript( render(:partial => "stats") ) %>").fadeIn();
 