config/routes.rb
Uif2013::Application.routes.draw do

  resources :shifts
  resources :department_trainings
  resources :volunteer_trainings
  resources :volunteer_checks
  resources :notes

  #require 'api_constraints' 
  
  # Barcode scanning routes
  match 'checkin', :controller => 'home', :action => 'checkin', :as => :checkin
  match 'volunteer_checkin', :controller => 'home', :action => 'volunteer_checkin', :as => :volunteer_checkin
  match 'meals_served', :controller => 'event', :action => 'meals_served'
  
  # General Home
  match 'home' => 'home#index', :as => :home
  match 'about' => 'home#about', :as => :about
  match 'contact' => 'home#contact', :as => :contact
  match 'privacy' => 'home#privacy', :as => :privacy
  match 'search' => 'home#search', :as => :search
  match 'statistics' => 'home#statistics', :as => :statistics
  match 'today' => 'events#today', :as => :today
  match 'tomorrow' => 'events#tomorrow', :as => :tomorrow
  match 'past' => 'events#past', :as => :past
 # get "events/today"


  
  # mobile routes
  resources :tokens,:only => [:create, :destroy]
  match 'getToken' => 'tokens#create', :via => :post
  match 'destroyToken' => 'tokens#destroy', :via => :delete
  match 'ajax_allergies' => 'allergies#ajax_allergies', :via => :get
  match 'getTodaysEvents' => 'mobile#getTodaysEvents', :via => :get
  match 'createAttendances' => 'mobile#createAttendances', :via => :post
  match 'getPhoto' => 'mobile#getPhoto', :via => :post
  match 'searchForStudent' => 'mobile#searchForStudent', :via => :get
  match 'getProgramsAndSections' => 'mobile#getProgramsAndSections', :via => :get
  match 'createEvent' => 'mobile#createEvent', :via => :post
  
  # Notes
  match 'alerts' => 'notes#alerts', :as => :alerts
  match 'dismiss_note/:id' => 'notes#dismiss', :as => :dismiss_note
  
  # Special attendance routes
  match 'mark_attended/:id' => 'events#mark_attended', :as => :mark_attended
  match 'mark_absent/:id' => 'events#mark_absent', :as => :mark_absent
  match 'mark_volunteer_attended/:id' => 'events#mark_volunteer_attended', :as => :mark_volunteer_attended
  match 'mark_volunteer_absent/:id' => 'events#mark_volunteer_absent', :as => :mark_volunteer_absent  

  # Drugs and conditions
  get "drug/index"


  #Generated model routes

  #resources :allergies
  resources :guardians do
    resources :notes
  end
  #resources :student_allergies
  resources :households do 
    resources :notes
  end
  resources :students do
    resources :notes
    get 'id', :on => :member
  end
  resources :drugs do
    resources :notes
  end
  resources :sections
  resources :attendances
  resources :locations do
    resources :notes
  end
  resources :events do
    resources :notes
    resources :shifts
    get 'meals_served', :on => :member
    get 'barcodes', :on => :member
  end
  resources :programs do
    resources :notes
    resources :shifts
  end
  resources :departments
  resources :enrollments
  resources :section_events
  #match 'volunteers/autocomplete_student_first_name' => 'volunteers#autocomplete_student_first_name'
  resources :volunteers do
    get :autocomplete_student_first_name, :on => :collection
    resources :notes
  end
  resources :trainings do
    resources:notes
  end
  resources :checks
  resources :conditions
  
  # Default URL
  root :to => 'home#index'
  
  # Authentication routes
  # resources :users
  devise_for :users
  # resources :sessions
  # match 'register' => 'users#new', :as => :register
  # match 'logout' => 'sessions#destroy', :as => :logout
  # match 'login' => 'sessions#new', :as => :login

end

app/models/volunteer_training.rb
class VolunteerTraining < ActiveRecord::Base
  attr_accessible :date, :training_id, :volunteer_id

    belongs_to :volunteer
    belongs_to :training

    validates_presence_of :date, :training_id, :volunteer_id


    scope :for_volunteer, lambda {|volunteer_id| where("volunteer_id = ?", volunteer_id) }
    scope :for_training, lambda {|training_id| where("training_id = ?", training_id) }

 
end

app/controllers/volunteer_trainings_controller.rb
class VolunteerTrainingsController < ApplicationController
    #before_filter :check_login
    # GET /volunteer_trainings
    # GET /volunteer_trainings.json
    before_filter :authenticate_user!
    def index
        @volunteer_trainings = VolunteerTraining.all
        
        respond_to do |format|
            format.html # index.html.erb
            format.json { render json: @volunteer_trainings }
        end
    end
    
    # GET /volunteer_trainings/1
    # GET /volunteer_trainings/1.json
    def show
        @volunteer_training = VolunteerTraining.find(params[:id])
        
        respond_to do |format|
            format.html # show.html.erb
            format.json { render json: @volunteer_training }
        end
    end
    
    # GET /volunteer_trainings/new
    # GET /volunteer_trainings/new.json
    def new
        @volunteer_training = VolunteerTraining.new
        
        respond_to do |format|
            format.html # new.html.erb
            format.json { render json: @volunteer_training }
        end
    end
    
    # GET /volunteer_trainings/1/edit
    def edit
        @volunteer_training = VolunteerTraining.find(params[:id])
    end
    
    # POST /volunteer_trainings
    # POST /volunteer_trainings.json
    def create

        @volunteer_training = VolunteerTraining.new(params[:volunteer_training])
        @volunteer = @volunteer_training.volunteer

        if @volunteer_training.save
            # if saved to database
            flash[:notice] = "Successfully created Volunteer Training."
            redirect_to @volunteer # go to show volunteer page
            else
            # return to the 'new' form
            render :action => 'new'
        end
    end
    
    # PUT /volunteer_trainings/1
    # PUT /volunteer_trainings/1.json
    def update
        @volunteer_training = VolunteerTraining.find(params[:id])
        @volunteer = @volunteer_training.volunteer
        respond_to do |format|
            if @volunteer_training.update_attributes(params[:volunteer_training])
                format.html { redirect_to @volunteer, notice: 'Volunteer Training was successfully updated.' }
                format.json { head :no_content }
                else
                format.html { render action: "edit" }
                format.json { render json: @volunteer_training.errors, status: :unprocessable_entity }
            end
        end
    end
    
    # DELETE /volunteer_trainings/1
    # DELETE /volunteer_trainings/1.json
    def destroy
        @volunteer_training = VolunteerTraining.find(params[:id])
        @training = VolunteerTraining.find(params[:id]).training

        @volunteer_training.destroy
        flash[:notice] = "Successfully removed volunteer_training from the UIF system."
        redirect_to @training
    end
end

app/views/volunteer_trainings/_form.html.erb
<%= simple_form_for(@volunteer_training) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :volunteer_id, :collection => Volunteer.alphabetical, :prompt => 'Choose Volunteer' %>
    <%= f.input :training_id, :collection => Training.alphabetical, :prompt => 'Choose Training' %>
<%= f.input :date, :order => [:month, :day, :year], :start_year => Date.today.year-10, :end_year => Date.today.year %>
  
</div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/volunteer_trainings/edit.html.erb
<h1>Editing Volunteer Training</h1>

<%= render 'form' %>

app/views/volunteer_trainings/index.html.erb
<h1>Listing Volunteer Trainings</h1>

<table>
  <tr>
    <th>Volunteer</th>
    <th>Training</th>
    <th>Date</th>
    <th></th>
    <th></th>
  </tr>

<% @volunteer_trainings.each do |volunteer_training| %>
  <tr>
    <td><%= link_to volunteer_training.volunteer.name, volunteer_path(volunteer_training.volunteer) %></td>

    <td><%= volunteer_training.training.name %></td>
    <td><%= volunteer_training.date.strftime("%B %d, %Y") %></td>
    <td><%= link_to 'Show', volunteer_training %></td>
    <td><%= link_to 'Edit', edit_volunteer_training_path(volunteer_training) %></td>
    <td><%= link_to 'Destroy', volunteer_training, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Volunteer Training', new_volunteer_training_path %>

app/views/volunteer_trainings/new.html.erb
<h1>New volunteer training</h1>

<%= render 'form' %>

app/views/volunteer_trainings/show.html.erb
<p>
  <b>Volunteer:</b>
  <%= @volunteer_training.volunteer_id %>
</p>

<p>
  <b>Training:</b>
  <%= @volunteer_training.training_id %>
</p>


<%= link_to 'Edit', edit_volunteer_training_path(@volunteer_training) %> |
<%= link_to 'Back', volunteers_path %>