config/routes.rb
Uif2013::Application.routes.draw do

  resources :shifts
  resources :department_trainings
  resources :volunteer_trainings
  resources :volunteer_checks
  resources :notes

  #require 'api_constraints' 
  
  # Barcode scanning routes
  match 'checkin', :controller => 'home', :action => 'checkin', :as => :checkin
  match 'volunteer_checkin', :controller => 'home', :action => 'volunteer_checkin', :as => :volunteer_checkin
  match 'meals_served', :controller => 'event', :action => 'meals_served'
  
  # General Home
  match 'home' => 'home#index', :as => :home
  match 'about' => 'home#about', :as => :about
  match 'contact' => 'home#contact', :as => :contact
  match 'privacy' => 'home#privacy', :as => :privacy
  match 'search' => 'home#search', :as => :search
  match 'statistics' => 'home#statistics', :as => :statistics
  match 'today' => 'events#today', :as => :today
  match 'tomorrow' => 'events#tomorrow', :as => :tomorrow
  match 'past' => 'events#past', :as => :past
 # get "events/today"


  
  # mobile routes
  resources :tokens,:only => [:create, :destroy]
  match 'getToken' => 'tokens#create', :via => :post
  match 'destroyToken' => 'tokens#destroy', :via => :delete
  match 'ajax_allergies' => 'allergies#ajax_allergies', :via => :get
  match 'getTodaysEvents' => 'mobile#getTodaysEvents', :via => :get
  match 'createAttendances' => 'mobile#createAttendances', :via => :post
  match 'getPhoto' => 'mobile#getPhoto', :via => :post
  match 'searchForStudent' => 'mobile#searchForStudent', :via => :get
  match 'getProgramsAndSections' => 'mobile#getProgramsAndSections', :via => :get
  match 'createEvent' => 'mobile#createEvent', :via => :post
  
  # Notes
  match 'alerts' => 'notes#alerts', :as => :alerts
  match 'dismiss_note/:id' => 'notes#dismiss', :as => :dismiss_note
  
  # Special attendance routes
  match 'mark_attended/:id' => 'events#mark_attended', :as => :mark_attended
  match 'mark_absent/:id' => 'events#mark_absent', :as => :mark_absent
  match 'mark_volunteer_attended/:id' => 'events#mark_volunteer_attended', :as => :mark_volunteer_attended
  match 'mark_volunteer_absent/:id' => 'events#mark_volunteer_absent', :as => :mark_volunteer_absent  

  # Drugs and conditions
  get "drug/index"


  #Generated model routes

  #resources :allergies
  resources :guardians do
    resources :notes
  end
  #resources :student_allergies
  resources :households do 
    resources :notes
  end
  resources :students do
    resources :notes
    get 'id', :on => :member
  end
  resources :drugs do
    resources :notes
  end
  resources :sections
  resources :attendances
  resources :locations do
    resources :notes
  end
  resources :events do
    resources :notes
    resources :shifts
    get 'meals_served', :on => :member
    get 'barcodes', :on => :member
  end
  resources :programs do
    resources :notes
    resources :shifts
  end
  resources :departments
  resources :enrollments
  resources :section_events
  #match 'volunteers/autocomplete_student_first_name' => 'volunteers#autocomplete_student_first_name'
  resources :volunteers do
    get :autocomplete_student_first_name, :on => :collection
    resources :notes
  end
  resources :trainings do
    resources:notes
  end
  resources :checks
  resources :conditions
  
  # Default URL
  root :to => 'home#index'
  
  # Authentication routes
  # resources :users
  devise_for :users
  # resources :sessions
  # match 'register' => 'users#new', :as => :register
  # match 'logout' => 'sessions#destroy', :as => :logout
  # match 'login' => 'sessions#new', :as => :login

end

app/models/volunteer_check.rb
class VolunteerCheck < ActiveRecord::Base
  require 'date'
  attr_accessible :approved, :check_id, :date_completed, :date_submitted, :notes, :paid, :volunteer_id

    belongs_to :volunteer
    belongs_to :check
    
    validates_presence_of :check_id, :volunteer_id
    
    scope :pending, where('date_completed IS NULL')
    scope :completed, where('date_completed IS NOT NULL')
 

	def self.expiring
		VolunteerCheck.completed.select{ |vc| (( vc.date_completed + vc.check.duration.months ) - Date.today).to_i < 30}
	end



end

app/controllers/volunteer_checks_controller.rb
class VolunteerChecksController < ApplicationController
    #before_filter :check_login
    # GET /volunteer_checks
    # GET /volunteer_checks.json
    before_filter :authenticate_user!
    def index
        @volunteer_checks = VolunteerCheck.all
        
        respond_to do |format|
            format.html # index.html.erb
            format.json { render json: @volunteer_checks }
        end
    end
    
    # GET /volunteer_checks/1
    # GET /volunteer_checks/1.json
    def show
        @volunteer_check = VolunteerCheck.find(params[:id])
        
        respond_to do |format|
            format.html # show.html.erb
            format.json { render json: @volunteer_check }
        end
    end
    
    # GET /volunteer_checks/new
    # GET /volunteer_checks/new.json
    def new
        @volunteer_check = VolunteerCheck.new
        
        respond_to do |format|
            format.html # new.html.erb
            format.json { render json: @volunteer_check }
        end
    end
    
    # GET /volunteer_checks/1/edit
    def edit
        @volunteer_check = VolunteerCheck.find(params[:id])
    end
    
    # POST /volunteer_checks
    # POST /volunteer_checks.json
    def create

        @volunteer_check = VolunteerCheck.new(params[:volunteer_check])
        @volunteer = @volunteer_check.volunteer

        if @volunteer_check.save
            # if saved to database
            flash[:notice] = "Successfully created Volunteer Check."
            redirect_to @volunteer # go to show volunteer page
            else
            # return to the 'new' form
            render :action => 'new'
        end
    end
    
    # PUT /volunteer_checks/1
    # PUT /volunteer_checks/1.json
    def update
        @volunteer_check = VolunteerCheck.find(params[:id])
        @volunteer = @volunteer_check.volunteer
        respond_to do |format|
            if @volunteer_check.update_attributes(params[:volunteer_check])
                format.html { redirect_to @volunteer, notice: 'Volunteer Check was successfully updated.' }
                format.json { head :no_content }
                else
                format.html { render action: "edit" }
                format.json { render json: @volunteer_check.errors, status: :unprocessable_entity }
            end
        end
    end
    
    # DELETE /volunteer_checks/1
    # DELETE /volunteer_checks/1.json
    def destroy
        @volunteer_check = VolunteerCheck.find(params[:id])
        @check = VolunteerCheck.find(params[:id]).check

        @volunteer_check.destroy
        flash[:notice] = "Successfully removed Volunteer Check from the UIF system."
        redirect_to @check
    end
end

app/views/volunteer_checks/_form.html.erb
<%= simple_form_for(@volunteer_check) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :volunteer_id, :collection => Volunteer.alphabetical, :prompt => 'Choose Volunteer' %>
    <%= f.input :check_id, :collection => Check.alphabetical, :prompt => 'Choose Check' %>
	<%= f.input :date_submitted, :order => [:month, :day, :year], :start_year => Date.today.year-10, :end_year => Date.today.year %>
	<%= f.input :date_completed, :order => [:month, :day, :year], :start_year => Date.today.year-10, :end_year => Date.today.year, :include_blank => true %>
	<%= f.input :paid %>
	<%= f.input :approved %>
    <%= f.input :notes %>

      
</div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/volunteer_checks/edit.html.erb
<h1>Editing Volunteer Check</h1>

<%= render 'form' %>

app/views/volunteer_checks/index.html.erb
<h1>Listing Volunteer Checks</h1>

<table>
  <tr>
    <th>Volunteer</th>
    <th>Check</th>
    <th>Date Submitted</th>
    <th>Date Completed</th>
    <th>Paid</th>
    <th>Approved</th>
    <th>Notes</th>
    <th></th>
    <th></th>
  </tr>

<% @volunteer_checks.each do |volunteer_check| %>
  <tr>
    <td><%= link_to volunteer_check.volunteer.name, volunteer_path(volunteer_check.volunteer) %></td>

    <td><%= volunteer_check.check.name %></td>
    <td><%= volunteer_check.date_submitted.strftime("%B %d, %Y") %></td>
    <td><%= volunteer_check.date_completed.strftime("%B %d, %Y") %></td>
    <td><%= volunteer_check.paid %></td>
    <td><%= volunteer_check.approved %></td>
    <td><%= volunteer_check.notes %></td>

    <td><%= link_to 'Show', volunteer_check %></td>
    <td><%= link_to 'Edit', edit_volunteer_check_path(volunteer_check) %></td>
    <td><%= link_to 'Destroy', volunteer_check, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Volunteer Check', new_volunteer_check_path %>

app/views/volunteer_checks/new.html.erb
<h1>New volunteer check</h1>

<%= render 'form' %>

app/views/volunteer_checks/show.html.erb
<p>
  <b>Volunteer:</b>
  <%= @volunteer_check.volunteer_id %>
</p>

<p>
  <b>Check:</b>
  <%= @volunteer_check.check_id %>
</p>


<%= link_to 'Edit', edit_volunteer_check_path(@volunteer_check) %> |
<%= link_to 'Back', volunteers_path %>